### PR TITLE
refactor(ezpz-flexbox-grid): update Sass functions to use modern modu…

### PR DESCRIPTION
**Pull request by frederikkempe**
# Update Sass functions to use modern module syntax  

This PR updates our Sass codebase to address upcoming deprecations in Dart Sass 3.0.0. The changes focus on migrating from global built-in functions to their newer, namespaced equivalents, as well as addressing specific deprecations like `type-of` and `map-get`.  

---

## Why are we making these changes?  

Sass is evolving to improve organization and prevent naming conflicts by deprecating global built-in functions. These changes ensure compatibility with Dart Sass 3.0.0, avoiding breaking changes and keeping our codebase up-to-date.  

---

### Module imports  

Adding necessary module imports at the top of Sass files that use these functions:  

```scss
@use "sass:list";
@use "sass:map";
@use "sass:meta";
```

## Updated function calls  

Replacing deprecated global functions with their module-based counterparts:  

- `length($list)` → `list.length($list)`  
- `map-has-key($map, $key)` → `map.has-key($map, $key)`  
- `map-get($map, $key)` → `map.get($map, $key)`  
- `type-of($value)` → `meta.type-of($value)`  

#### Before:  

```scss
$total-cells: length($ezpz-fractions);  
flex-direction: #{map-get($values, $value)};  
@if (type-of($value) != number) { ... }
```

### After:  

```scss
$total-cells: list.length($ezpz-fractions);  
flex-direction: #{map.get($values, $value)};  
@if (meta.type-of($value) != number) { ... }
```

## Ensuring backwards compatibility  

These updates do not alter functionality but make the code future-proof for Dart Sass 3.0.0.  

---

## What are the benefits?  

- **Future-proofing the codebase to avoid breaking changes.**  
- **Aligning with modern Sass best practices for better maintainability and clarity.**  

This proactive approach ensures smooth transitions and keeps our code in line with the latest standards.

### CODE REVIEW

**Comment by ghost** [comment]
Hi, thanks for this PR. We don't use this library anymore, but we will look into it. :)

**Comment by frederikkempe** [comment]
@bas-vi That would be great! If you don’t mind me asking, what do you currently use instead of this library?

**Comment by ghost** [comment]
Of course, we just use vanilla [CSS grid](https://developer.mozilla.org/en-US/docs/Web/CSS/grid).

**Comment by frederikkempe** [comment]
@bas-vi Honestly, I thought about doing the same but couldn’t quite convince myself. Now, I’m actually convinced to give it a try. Thanks once again!

**Comment by ghost** [comment]
@frederikkempe Well, in the end I did update the library and examples. Thanks again.

**Comment by frederikkempe** [comment]
@bas-vi Thanks for your time and effort as well!

**Pull request merged**
